language: java

services:
    - docker

cache:
  directories:
  - $HOME/.m2

script: "mvn test package install exec:java cobertura:cobertura"

after_success:
  - ls -lh target/
  - tar -cvf target.tar target/
  - tar -tvf target.tar
